[update] matrix.rst
taichi-dev/taichi-docs-zh-cn pull request #104
Opened 2020-08-03 10:45 UTC by isdanni

### file changed
- `matrix.po`

### related issue

#101

2020-08-04 15:55 UTC, archibate requested changes
Thank for the quick response! I added few nits :rocket:

2020-08-04 15:55 UTC, archibate commented on locales/zh_CN/LC_MESSAGES/matrix.po
> +"# Now b = ti.Matrix([[2, 4], [3, 5]])"
```suggestion
"# 现在 b = ti.Matrix([[2, 4], [3, 5]])"
```

2020-08-04 15:55 UTC, archibate commented on locales/zh_CN/LC_MESSAGES/matrix.po
> +msgstr "（标量） ``a`` 矩阵的痕迹。"
```suggestion
msgstr "（标量） ``a`` 矩阵的迹。"
```
I thought it's a standard translation in many linalg textbooks... let's follow them.

2020-08-04 15:55 UTC, archibate commented on locales/zh_CN/LC_MESSAGES/matrix.po
> +msgstr "（标量） ``a`` 矩阵的决定因素。"
```suggestion
msgstr "（标量） ``a`` 矩阵的行列式。"
```
Please don't depend too much on machine translators :)

2020-08-04 15:55 UTC, archibate commented on locales/zh_CN/LC_MESSAGES/matrix.po
> +msgstr "矩阵的矩阵大小现在必须为 1x1、2x2、3x3 或 4x4。"
```suggestion
msgstr "目前用于此函数的矩阵大小必须为 1x1、2x2、3x3 或 4x4。"
```

2020-08-04 15:55 UTC, archibate commented on locales/zh_CN/LC_MESSAGES/matrix.po
> +msgstr "此功能目前仅在Taichi范围内有效。"
```suggestion
msgstr "此函数目前仅在 Taichi 作用域内有效。"
```

2020-08-04 15:55 UTC, archibate commented on locales/zh_CN/LC_MESSAGES/matrix.po
> +msgstr "（矩阵） ``a`` 的逆反矩阵。"
```suggestion
msgstr "（矩阵） ``a`` 的逆矩阵。"
```

2020-08-04 15:55 UTC, archibate commented on locales/zh_CN/LC_MESSAGES/matrix.po
> +msgstr "``all(A)``（仅Taichi范围）"
```suggestion
msgstr "``all(A)``（仅 Taichi 作用域）"
```

2020-08-04 15:55 UTC, archibate commented on locales/zh_CN/LC_MESSAGES/matrix.po
> +msgstr "``any(A)``（仅Taichi范围）"
```suggestion
msgstr "``any(A)``（仅 Taichi 作用域）"
```

2020-08-05 01:51 UTC, ArkhamWJZ reviewed
LGTM! + A few nits 🌈

2020-08-05 01:51 UTC, ArkhamWJZ commented on locales/zh_CN/LC_MESSAGES/matrix.po
>  msgstr "作为临时本地变量。一个由 ``n*m`` 个标量构成的 ``n×m`` 阶矩阵。"
```suggestion
msgstr "作为临时局部变量。一个由 ``n*m`` 个标量构成的 ``n×m`` 阶矩阵。"
```

2020-08-05 01:51 UTC, ArkhamWJZ commented on locales/zh_CN/LC_MESSAGES/matrix.po
> +msgstr "（可选、标量或元组）向量张量的形状，见 :ref:`tensor`"
```suggestion
msgstr "（可选，标量或元组）向量张量的形状，见 :ref:`tensor`"
```

2020-08-05 01:51 UTC, ArkhamWJZ commented on locales/zh_CN/LC_MESSAGES/matrix.po
> +msgstr "（可选、标量或元组）请参见 ： ref:`offset`"
```suggestion
msgstr "（可选，标量或元组）请参见 ： ref:`offset`"
```

2020-08-05 01:51 UTC, ArkhamWJZ commented on locales/zh_CN/LC_MESSAGES/matrix.po
> +"例如，这将创建一个 2x3 矩阵，在第一行中具有组件 (2, 3, 4) ，在第二行 (5, 6, 7) "
```suggestion
"例如，下述将创建一个 2x3 的矩阵，第一行中的分量为 (2, 3, 4) ，第二行的为 (5, 6, 7) "
```

2020-08-05 01:51 UTC, ArkhamWJZ commented on locales/zh_CN/LC_MESSAGES/matrix.po
>  msgstr "比如，以下代码通过将向量连接作为一个3x3矩阵的每一行（列）： ::"
```suggestion
msgstr "例如，以下代码创建了一个 3x3 矩阵，矩阵的行（列）是由向量拼接构成的： ::"
```

2020-08-05 01:51 UTC, ArkhamWJZ commented on locales/zh_CN/LC_MESSAGES/matrix.po
> +"# Taichi-scope\n"
```suggestion
"# Taichi 作用域\n"
```

2020-08-05 01:51 UTC, ArkhamWJZ commented on locales/zh_CN/LC_MESSAGES/matrix.po
> +"# to specify data in rows\n"
```suggestion
"# 指定行中的数据\n"
```

2020-08-05 01:51 UTC, ArkhamWJZ commented on locales/zh_CN/LC_MESSAGES/matrix.po
> +"# to specify data in columns instead\n"
```suggestion
"# 指定列中的数据\n"
```

2020-08-05 01:51 UTC, ArkhamWJZ commented on locales/zh_CN/LC_MESSAGES/matrix.po
> +"# lists can be used instead of vectors\n"
```suggestion
"# 可以用向量代替参数中的列表\n"
```

2020-08-05 01:51 UTC, ArkhamWJZ commented on locales/zh_CN/LC_MESSAGES/matrix.po
> +"# or\n"
```suggestion
"# 或者\n"
```

2020-08-05 01:51 UTC, ArkhamWJZ commented on locales/zh_CN/LC_MESSAGES/matrix.po
>  msgstr "第一对方括号中的下标找到张量中的矩阵;"
```suggestion
msgstr "第一对方括号中的索引定位张量中的矩阵;"
```

2020-08-05 01:51 UTC, ArkhamWJZ commented on locales/zh_CN/LC_MESSAGES/matrix.po
>  msgstr "第二对方括号中的下标找到矩阵中的标量元素。"
```suggestion
msgstr "第二对方括号中的索引定位矩阵中的标量元素。"
```

2020-08-05 01:51 UTC, ArkhamWJZ commented on locales/zh_CN/LC_MESSAGES/matrix.po
>  msgstr "对于0维的矩阵形式的张量，第一对方括号中的下标应该为 ``[None]`` 。"
```suggestion
msgstr "对于0维的矩阵形式的张量，第一对方括号中的索引应该为 ``[None]`` 。"
```

2020-08-05 03:12 UTC, ArkhamWJZ approved these changes

2020-08-05 05:18 UTC, archibate reviewed
Feel free to merge on your own after these minor issues are fixed :+1:

2020-08-05 05:18 UTC, archibate commented on locales/zh_CN/LC_MESSAGES/matrix.po
> +msgstr "（可选，标量或元组）请参见 ： ref:`offset`"
```suggestion
msgstr "（可选，标量或元组）请参见 :ref:`offset`"
```

2020-08-05 05:18 UTC, archibate commented on locales/zh_CN/LC_MESSAGES/matrix.po
> +"了矩阵形式的张量。"
```suggestion
"了由矩阵组成的张量。"
```

2020-08-05 05:18 UTC, archibate commented on locales/zh_CN/LC_MESSAGES/matrix.po
> +"# 可以用向量代替参数中的列表\n"
```suggestion
"# 可以用列表代替参数中的向量\n"
```

2020-08-05 05:40 UTC, merged