[更新完毕] dev_install
taichi-dev/taichi-docs-zh-cn pull request #109
Opened 2020-08-07 07:47 UTC by ArkhamWJZ

2020-08-07 08:36 UTC, isdanni reviewed
🚀 🚀 🚀

2020-08-07 08:36 UTC, isdanni commented on locales/zh_CN/LC_MESSAGES/dev_install.po
> +"请注意，本章节是为 Taichi 编程语言的编译器开发人员所准备。终端用户应该使用 pip 进"
```suggestion
"请注意，本章节是为 Taichi 语言编译器的开发人员所准备的。终端用户应该使用 pip 进"
```

2020-08-07 08:36 UTC, isdanni commented on locales/zh_CN/LC_MESSAGES/dev_install.po
> +"LLVM 可执行文件，它是否能正常工作取决于你的系统环境:"
```suggestion
"确保你已经安装了 LLVM 10.0.0。注意，Taichi 使用的是 **定制版 LLVM**，所以从 LLVM "
"官网或其他来源下载的预构建可执行文件可能不起作用。这里我们提供了 Taichi 的定制版 "
"LLVM 可执行文件，它是否能正常运行取决于你的系统环境:"
```

2020-08-07 08:36 UTC, isdanni commented on locales/zh_CN/LC_MESSAGES/dev_install.po
> +msgstr "添加或追加之前小节安装的 LLVM 可执行文件路径到 ``PATH``。"
```suggestion
msgstr "添加或附加之前章节安装的 LLVM 可执行文件路径到 ``PATH``。"
```

2020-08-09 01:27 UTC, archibate requested changes

2020-08-09 01:27 UTC, archibate commented on locales/zh_CN/LC_MESSAGES/dev_install.po
> +"安装，而不是从源代码开始构建。为支持在 NVIDIA GPU 上进行工程构建，CUDA 10.0+是必"
```suggestion
"安装，而不是从源代码开始构建。要在构建加入对 NVIDIA GPU 的支持，CUDA 10.0+是必"
```
Btw, @yuanming-hu I thought building with CUDA support doesn't need CUDA thanks to our `DynamicLoader`?

2020-08-09 01:27 UTC, archibate commented on locales/zh_CN/LC_MESSAGES/dev_install.po
> +"``$LLVM_FOLDER/lib/cmake/llvm``."
```suggestion
"在 Windows 下, 如果你使用的是 Taichi 版预构建的 LLVM, 请将 ``$LLVM_FOLDER/bin`` "
"添加到 ``PATH``。随后，当你使用 ``CMake`` 构建 Taichi 时，将 ``LLVM_DIR`` 设置为 "
"``$LLVM_FOLDER/lib/cmake/llvm``."
```

2020-08-09 01:27 UTC, archibate commented on locales/zh_CN/LC_MESSAGES/dev_install.po
> +msgstr "安装中的故障排除"
```suggestion
msgstr "开发者安装中的故障排除"
```

2020-08-09 01:27 UTC, archibate commented on locales/zh_CN/LC_MESSAGES/dev_install.po
> +"请尝试执行 ``git submodule update —init —recursive —depth=1``."
```suggestion
"请尝试执行 ``git submodule update --init --recursive --depth=1``."
```

2020-08-09 01:27 UTC, archibate commented on locales/zh_CN/LC_MESSAGES/dev_install.po
> +"请尝试将 ``TAICHI_REPO_DIR`` 添加到环境变量中, 详见 :ref:`dev_env_settings`."
```suggestion
"请尝试将 ``TAICHI_REPO_DIR`` 添加到环境变量中, 详见 :ref:`dev_env_settings` 。"
```

2020-08-09 01:27 UTC, archibate commented on locales/zh_CN/LC_MESSAGES/dev_install.po
> +"# 应该输出 /usr/local/bin/llvm-as 或 /opt/XXX/bin/llvm-as, 这是我们的配置文件所在"
```suggestion
"# 应该输出 /usr/local/bin/llvm-as 或 /opt/XXX/bin/llvm-as, 这是我们的定制版 LLVM 所在"
```

2020-08-15 12:32 UTC, merged