[翻译更新] utilities
taichi-dev/taichi-docs-zh-cn pull request #75
Opened 2020-06-01 15:36 UTC by liaopeiyuan

2020-06-01 16:00 UTC, archibate reviewed
Thank for updating! LGTM + nits.

2020-06-01 16:00 UTC, archibate commented on locales/zh_CN/LC_MESSAGES/utilities.po
> +"**快速定位存储器区段错误和断言错误** ``gdb``: 在Taichi 崩溃时，``gdb`` 会被响应"
We add English text in brackets to help Chinese users connect their knowledge in programming (e.g. `assert(x)`).
```suggestion
"使用 ``gdb`` **快速定位段错误 (segmentation fault) 和断言错误 (assertion failure)**: 在Taichi 崩溃时，``gdb`` 会被响应"
```

2020-06-01 16:00 UTC, archibate commented on locales/zh_CN/LC_MESSAGES/utilities.po
> +"（``backtrace``）指令检查堆的回溯，因而定位产生错误的代码的具体行数。"
```suggestion
"（``backtrace``）指令检查堆的回溯，从而定位产生错误的代码的具体行数。"
```

2020-06-01 16:00 UTC, archibate commented on locales/zh_CN/LC_MESSAGES/utilities.po
> +msgstr "建议 **the PR author** （Pull Request 的作者）运行回归测试的工作流程是："
```suggestion
msgstr "建议 **Pull Request 的作者** 运行回归测试的工作流程是："
```

2020-06-02 09:18 UTC, isdanni commented on locales/zh_CN/LC_MESSAGES/utilities.po
> +msgstr "开始尝试解决问题（第一阶段）。"
```suggestion
msgstr "尝试解决问题（第一阶段）。"
```

2020-06-02 09:21 UTC, isdanni commented on locales/zh_CN/LC_MESSAGES/utilities.po
> +"启动并附着到当前的线程上。您可能需要输入和 ``sudo`` 超级用户权限相关的密码来允"
```suggestion
"使用 ``gdb`` **快速定位段错误 (segmentation fault) 和断言错误 (assertion failure)**: 在Taichi 崩溃时，``gdb`` 会被"
"触发并附着到当前的线程上。您可能需要输入和 ``sudo`` 超级用户权限相关的密码来允"
```

2020-06-02 09:23 UTC, isdanni approved these changes
Thanks for the contribution! Just a few nips :-)

btw sorry for the delay..:skull::skull::skull:spilt water on my computer & spent two days fixing it

2020-06-02 21:12 UTC, rexwangcc requested changes
LGTM in general!! Could you help fix the typo that was introduced before as well? Thanks!

2020-06-02 21:12 UTC, rexwangcc commented on locales/zh_CN/LC_MESSAGES/utilities.po
>  msgstr "你可以使用 ``TI_IO`` 宏来显式定义太极拳中必要的字段。"
Hmm, let's remove the `拳` and use `Taichi` here 🤣  (It's not what this PR changed, but might be better to fix ASAP...)

2020-06-03 03:10 UTC, rexwangcc approved these changes

2020-06-14 04:42 UTC, merged